### ISSUE TITLE
NTP integration

### ISSUE THREAD

**Issue by cchance27** [rhagman/sustainable-green-plants#10]
Instead of using the reset button to set 20:00 would recommend if theirs memory available to integrate NTPclient to pull the real time, especially since the D1 already has wifi, i mean you can leave the reset and on boot 20:00 but would be cool if the NTPclient synced everything, especially once you move to modular and have perhaps multiple sensors all synced.

http://playground.arduino.cc/Code/NTPclient

**Comment by rhagman** [comment]
I'll close this issue and link it to #18 so that we can have this in mind when updating the software. This is probably one of the first features that will be included once we start to work with the software! Thanks for contributing to the project, if you would like to join the development chat, then send message with your email and I'll send you an invite to slack! Have a nice day!
